name: Get Branch Name, Commit Hash, Commits, and Changes

on:
  push:
    branches:
      - '*'

jobs:
  get-branch-name-commit-hash-commits-and-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Log start of script
        run: echo "GitHub Actions script is starting..."

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get branch name
        id: branch
        run: echo "::set-output name=branch_name::$(echo $GITHUB_REF | cut -d/ -f3-)"

      - name: Get latest commit hash
        id: commit
        run: |
          echo "::set-output name=commit_hash::$(git log -1 --pretty=format:'%h')"
          echo "::set-output name=commit_author::$(git log -1 --pretty=format:'%an')"

      - name: Make API call and Log branch name, commit hash, and GitHub ref
        run: |
          # Retrieve outputs from previous steps
          branch_name="${{ steps.branch.outputs.branch_name }}"
          commit_hash="${{ steps.commit.outputs.commit_hash }}"
          commit_author="${{ steps.commit.outputs.commit_author }}"
          user_id="${{ secrets.USER_ID }}"

          # Constructing the JSON payload for the API call
          api_url="https://be-webmaster-portal-dev-backend.onrender.com/graphql"

          # First API call to get questionId
          questionIdResponse=$(curl --location "$api_url" \
          --header 'Content-Type: application/json' \
          --data '{"query":"query GetQuestionIdByBranchName($branchName: String) { getQuestionIdByBranchName(branchName: $branchName) { questionId response { message status } }}","variables":{"branchName":"'"$branch_name"'"}}')

          # Extracting questionId field value using jq
          questionId=$(echo "$questionIdResponse" | jq -r '.data.getQuestionIdByBranchName.questionId')

          echo "Question ID: $questionId"

          # Second API call for upserting GitHub data
          response=$(curl --location "$api_url" \
          --header 'Content-Type: application/json' \
          --data '{"query":"mutation Mutation($input: UserGithubDataInputType) { upsertUserGithubData(input: $input) { response { status message } data { commitHash branchRef branchName userId commitAuthor questionId } }}","variables":{"input":{"commitHash":"'"$commit_hash"'","branchRef": "'"$GITHUB_REF"'","branchName": "'"$branch_name"'","userId": "'"$user_id"'","commitAuthor": "'"$commit_author"'","questionId": "'"$questionId"'"}}}')

          # Logging the API response and branch details
          echo "API Response: $response"
          echo "Branch Name: $branch_name, Commit Hash: $commit_hash, Commit Author: $commit_author, GitHub Ref: $GITHUB_REF, userId: $user_id"
